backend:
  name: github
  repo: github.com/21stAmendmentBrewery/soma-website # Replace with your repo
  branch: master

media_folder: "src/img/gallery" # Folder where user uploaded files should go
public_folder: "img/gallery"
